from __future__ import annotations

import secrets
from collections.abc import Callable
from pathlib import Path

DESKTOP_DEFAULTS: dict[str, Callable[[], str]] = {
    "YUXI_ENV": lambda: "production",
    "JWT_SECRET_KEY": lambda: secrets.token_hex(32),
    "YUXI_INSTANCE_ID": lambda: f"instance-{secrets.token_hex(8)}",
    "POSTGRES_USER": lambda: "postgres",
    "POSTGRES_PASSWORD": lambda: secrets.token_hex(24),
    "POSTGRES_DB": lambda: "yuxi",
    "NEO4J_USERNAME": lambda: "neo4j",
    "NEO4J_PASSWORD": lambda: secrets.token_hex(24),
    "MINIO_ACCESS_KEY": lambda: f"yuxi{secrets.token_hex(8)}",
    "MINIO_SECRET_KEY": lambda: secrets.token_hex(24),
}


def _parse_assignment(raw_line: str) -> tuple[str, str] | None:
    line = raw_line.strip()
    if not line or line.startswith("#") or "=" not in line:
        return None
    key, value = line.split("=", 1)
    return key.strip(), value.strip()


def _parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        parsed = _parse_assignment(raw_line)
        if parsed:
            key, value = parsed
            values[key] = value
    return values


def _render_env_line(key: str) -> str:
    return f"{key}={DESKTOP_DEFAULTS[key]()}"


def _uses_desktop_defaults(template_values: dict[str, str]) -> bool:
    return "JWT_SECRET_KEY" in template_values or "YUXI_INSTANCE_ID" in template_values


def _build_new_env(template_text: str) -> tuple[str, int]:
    template_lines = template_text.splitlines()
    template_values = {
        key: value
        for raw_line in template_lines
        if (parsed := _parse_assignment(raw_line))
        for key, value in [parsed]
    }
    use_desktop_defaults = _uses_desktop_defaults(template_values)
    seen: set[str] = set()
    output: list[str] = []

    for raw_line in template_lines:
        parsed = _parse_assignment(raw_line)
        if not parsed:
            output.append(raw_line)
            continue
        key, value = parsed
        seen.add(key)
        if use_desktop_defaults and (key == "YUXI_ENV" or (key in DESKTOP_DEFAULTS and not value)):
            output.append(_render_env_line(key))
        else:
            output.append(raw_line)

    if use_desktop_defaults:
        missing_keys = [key for key in DESKTOP_DEFAULTS if key not in seen]
        if missing_keys:
            output.append("")
            output.append("# Generated by Yuxi Desktop Launcher")
            output.extend(_render_env_line(key) for key in missing_keys)

    rendered = "\n".join(output).rstrip() + "\n"
    return rendered, len(_parse_text_env(rendered))


def _parse_text_env(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw_line in text.splitlines():
        parsed = _parse_assignment(raw_line)
        if parsed:
            key, value = parsed
            values[key] = value
    return values


def initialize_env(project_dir: Path) -> tuple[Path, int]:
    template = project_dir / ".env.template"
    target = project_dir / ".env.desktop"
    if not template.exists():
        raise FileNotFoundError(f"缺少配置模板: {template}")

    template_text = template.read_text(encoding="utf-8")
    template_values = _parse_text_env(template_text)
    use_desktop_defaults = _uses_desktop_defaults(template_values)

    if not target.exists():
        rendered, count = _build_new_env(template_text)
        target.write_text(rendered, encoding="utf-8")
        return target, count

    current = _parse_env(target)
    updated_lines: list[str] = []
    changed = 0
    for raw_line in target.read_text(encoding="utf-8").splitlines():
        parsed = _parse_assignment(raw_line)
        if use_desktop_defaults and parsed:
            key, value = parsed
            if key == "YUXI_ENV" and value != "production":
                updated_lines.append(_render_env_line(key))
                changed += 1
                continue
            if key in DESKTOP_DEFAULTS and not value:
                updated_lines.append(_render_env_line(key))
                changed += 1
                continue
        updated_lines.append(raw_line)

    missing_lines: list[str] = []
    for raw_line in template_text.splitlines():
        parsed = _parse_assignment(raw_line)
        if not parsed:
            continue
        key, _ = parsed
        if key not in current:
            if use_desktop_defaults and key in DESKTOP_DEFAULTS:
                missing_lines.append(_render_env_line(key))
            else:
                missing_lines.append(raw_line)

    if use_desktop_defaults:
        known_keys = current.keys() | {line.split("=", 1)[0] for line in missing_lines}
        for key in DESKTOP_DEFAULTS:
            if key not in known_keys:
                missing_lines.append(_render_env_line(key))

    if missing_lines:
        updated_lines.append("")
        updated_lines.append("# Added by Yuxi Desktop Launcher")
        updated_lines.extend(missing_lines)

    if changed or missing_lines:
        target.write_text("\n".join(updated_lines).rstrip() + "\n", encoding="utf-8")
    return target, changed + len(missing_lines)
